import React from "react";
const Mail="";
const Data=[
    [[
    "https://www.cloudskillsboost.google/course_templates/754/labs/461560",
    "https://drive.google.com/file/d/1TfOpc0H1vJ0NImM0P1S3VEE9xj6g5Us9/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Hosting%20a%20Web%20App%20on%20Google%20Cloud%20Using%20Compute%20Engine/Hosting%20a%20Web%20App%20on%20Google%20Cloud%20Using%20Compute%20Engine.md"
    ],
    [
    "https://www.cloudskillsboost.google/course_templates/754/labs/461561",
    "https://drive.google.com/file/d/1pOI6iwZbPEuJa-SJpnKSs4-hE9DrmOHe/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Creating%20a%20Persistent%20Disk/Creating%20a%20Persistent%20Disk.md"  
    ],
    [
    "https://www.cloudskillsboost.google/course_templates/754/labs/461562",
    "https://drive.google.com/file/d/1-XPLi2FfuydLelqJXQ9VCh-LDSXcP_g1/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Hosting%20a%20Web%20App%20on%20Google%20Cloud%20Using%20Compute%20Engine/Hosting%20a%20Web%20App%20on%20Google%20Cloud%20Using%20Compute%20Engine.md"  
    ],
    [
    "https://www.cloudskillsboost.google/course_templates/754/labs/461563",
    "https://drive.google.com/file/d/1qmtwcS_LDMx6o81ncF57Z_k68LmpSDoZ/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/The%20Basics%20of%20Google%20Cloud%20Compute%20Challenge%20Lab/The%20Basics%20of%20Google%20Cloud%20Compute%20Challenge%20Lab.md"
    ]],
    [[
    "https://www.cloudskillsboost.google/course_templates/662/labs/461584",
    "https://drive.google.com/file/d/1DbytCSHV5ChANYNY_SaSgkC8-ca4dvUF/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/API%20Gateway%20Qwik%20Start/API%20Gateway%20Qwik%20Start.md"
    ],
    [
    "https://www.cloudskillsboost.google/course_templates/662/labs/461585A",
    "https://drive.google.com/file/d/192aaFZxROafNdoAl9ixYr1ZbOmA_G48M/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Google%20Cloud%20PubSub%20Qwik%20Start%20-%20Console/Google%20Cloud%20PubSub%20Qwik%20Start%20-Console.md"  
    ],
    [
    "https://www.cloudskillsboost.google/course_templates/662/labs/461586",
    "https://drive.google.com/file/d/1tXbMRNZjHL1LTjlxjEMjMiVvGocJ3Dog/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Cloud%20Functions%20Qwik%20Start%20-%20Console/Cloud%20Functions%20Qwik%20Start%20-%20Console.md"  
    ],
    [
    "https://cloudskillsboost.google/course_templates/662/labs/461587",
    "https://drive.google.com/file/d/1d2hHf5ilFgrKHJW0ob2c7rdd8Rw24zD7/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Getting%20Started%20with%20API%20Gateway%20Challenge%20Lab/Getting%20Started%20with%20API%20Gateway%20Challenge%20Lab.md"
    ]],
    [[
    "https://www.cloudskillsboost.google/games/5516",
    "",
    "" 
    ]],
    [[
    "https://www.cloudskillsboost.google/games/5516",
    "",
    "" 
    ]],
    [[
    "https://www.cloudskillsboost.google/course_templates/662/labs/461584",
    "https://drive.google.com/file/d/1DbytCSHV5ChANYNY_SaSgkC8-ca4dvUF/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/API%20Gateway%20Qwik%20Start/API%20Gateway%20Qwik%20Start.md"
    ],
    [
    "https://www.cloudskillsboost.google/course_templates/662/labs/461585A",
    "https://drive.google.com/file/d/192aaFZxROafNdoAl9ixYr1ZbOmA_G48M/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Google%20Cloud%20PubSub%20Qwik%20Start%20-%20Console/Google%20Cloud%20PubSub%20Qwik%20Start%20-Console.md"  
    ],
    [
    "https://www.cloudskillsboost.google/course_templates/662/labs/461586",
    "https://drive.google.com/file/d/1tXbMRNZjHL1LTjlxjEMjMiVvGocJ3Dog/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Cloud%20Functions%20Qwik%20Start%20-%20Console/Cloud%20Functions%20Qwik%20Start%20-%20Console.md"  
    ],
    [
    "https://www.cloudskillsboost.google/course_templates/662/labs/461587",
    "https://drive.google.com/file/d/1d2hHf5ilFgrKHJW0ob2c7rdd8Rw24zD7/view",
    "https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/main/Getting%20Started%20with%20API%20Gateway%20Challenge%20Lab/Getting%20Started%20with%20API%20Gateway%20Challenge%20Lab.md"
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]],
    [[
    "",
    "",
    ""
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""  
    ],
    [
    "",
    "",
    ""
    ]]

]

export default Data;